### ISSUE TITLE
Help With Workflow

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/InquiryStream-Language-Pack#1]
I know feel like there must be some magical way to do this. I have this translation file from version 2.2 and now 2.3 has come out with a number of additional strings that need to be translated as well. What's the best way to take the work I've already completed, merge it with a new .po file, so that I don't have to translate everything all over again, but just have to translate the newly added strings?

**Comment by r-a-y** [comment]
Do you use PoEdit?

If so, check out this article:
`http://www.marketpressthemes.com/blog/how-to-merge-two-po-files-using-poedit/`

If not, let me know what you usually use to create a language file.

**Comment by mrjarbenne** [comment]
I do, and I will. Thanks for that.
